/**
 * @fileoverview Ticket ID generator for TVK Constituency Complaint Portal.
 * Generates unique ticket IDs in the format: TVK-YYYY-NNNNN
 *
 * The database trigger (trg_generate_ticket_id) handles ticket generation
 * server-side. This module provides client-side utilities for display and
 * validation.
 */

/**
 * Generates a ticket ID string in TVK-YYYY-NNNNN format.
 * Used for display/preview purposes — the actual ticket_id is
 * generated by the PostgreSQL trigger on INSERT.
 *
 * @param sequenceNumber - The sequence number (1-99999)
 * @param year - Optional year override (defaults to current year)
 * @returns Formatted ticket ID string
 *
 * @example
 * generateTicketId(1)     // => "TVK-2026-00001"
 * generateTicketId(42)    // => "TVK-2026-00042"
 * generateTicketId(123, 2025) // => "TVK-2025-00123"
 */
export function generateTicketId(sequenceNumber: number, year?: number): string {
  const ticketYear = year ?? new Date().getFullYear();
  const paddedSeq = String(sequenceNumber).padStart(5, '0');
  return `TVK-${ticketYear}-${paddedSeq}`;
}

/**
 * Validates whether a string is a valid TVK ticket ID.
 *
 * @param ticketId - The ticket ID string to validate
 * @returns True if the format matches TVK-YYYY-NNNNN
 *
 * @example
 * isValidTicketId("TVK-2026-00001") // => true
 * isValidTicketId("tvk-2026-1")     // => false
 * isValidTicketId("ABC-2026-00001") // => false
 */
export function isValidTicketId(ticketId: string): boolean {
  const pattern = /^TVK-\d{4}-\d{5}$/;
  return pattern.test(ticketId);
}

/**
 * Extracts the year from a TVK ticket ID.
 *
 * @param ticketId - The ticket ID string
 * @returns The year portion, or null if invalid
 *
 * @example
 * extractTicketYear("TVK-2026-00001") // => 2026
 */
export function extractTicketYear(ticketId: string): number | null {
  if (!isValidTicketId(ticketId)) return null;
  return parseInt(ticketId.split('-')[1], 10);
}

/**
 * Extracts the sequence number from a TVK ticket ID.
 *
 * @param ticketId - The ticket ID string
 * @returns The sequence number, or null if invalid
 *
 * @example
 * extractTicketSequence("TVK-2026-00042") // => 42
 */
export function extractTicketSequence(ticketId: string): number | null {
  if (!isValidTicketId(ticketId)) return null;
  return parseInt(ticketId.split('-')[2], 10);
}

/** Ticket ID prefix */
export const TICKET_PREFIX = 'TVK';

/** Current ticket year */
export const TICKET_YEAR = new Date().getFullYear();
